import type { CardDefinitionId } from '../../model/types';

export const DEFAULT_DECK: CardDefinitionId[] = [
  'forest',
  'forest',
  'forest',
  'forest',
  'forest',
  'forest',
  'mountain',
  'mountain',
  'mountain',
  'mountain',
  'mountain',
  'mountain',
  'grizzly-bears',
  'grizzly-bears',
  'hill-giant',
  'hill-giant',
  'lightning-bolt',
  'lightning-bolt',
  'lightning-strike',
  'lightning-strike',
  'savannah-lions',
  'savannah-lions',
  'goblin-piker',
  'goblin-piker',
  'llanowar-elves',
  'llanowar-elves',
  'dark-banishing',
  'dark-banishing',
  'healing-salve',
] as CardDefinitionId[];
